from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass
from typing import Any

from app.core.config import Settings
from app.domain.enums import TransitionType
from app.domain.schemas import (
    CutResultMessage,
    FrameBatchMetadata,
    SceneInterval,
    Transition,
)
from app.infrastructure.ray_store import RayObjectStore
from app.infrastructure.redis_streams import RedisStreams, StreamMessage
from app.infrastructure.serialization import (
    model_to_stream_fields,
    stream_fields_to_model,
)
from app.workers.common import StreamWorker, run_worker

logger = logging.getLogger(__name__)

CUT_STATE_PREFIX = "cv:ml:cut-state"
CUT_RESULT_CACHE_PREFIX = "cv:ml:cut-result"
ACTOR_NAMESPACE = "cv-video-analysis-models"


@dataclass(frozen=True, slots=True)
class CutSceneState:
    next_chunk_index: int
    active_scene_number: int


def _scene_number(scene_id: str) -> int:
    try:
        return int(scene_id.rsplit(":", 1)[1])
    except (IndexError, ValueError) as exc:
        raise ValueError(
            f"Invalid scene_id generated by cut worker: {scene_id}"
        ) from exc


def _deduplicate_owned_cuts(
    batch: FrameBatchMetadata,
    detections: list[dict[str, Any]],
) -> list[tuple[int, float]]:
    owned: dict[int, float] = {}
    for detection in detections:
        local_frame = int(detection["local_frame"])
        if not 0 <= local_frame < batch.frame_count:
            raise ValueError(
                f"Cut model returned local frame {local_frame} outside the tensor"
            )
        global_frame = batch.context_start_frame + local_frame
        if not batch.valid_start_frame <= global_frame <= batch.valid_end_frame:
            continue
        confidence = min(1.0, max(0.0, float(detection["confidence"])))
        owned[global_frame] = max(confidence, owned.get(global_frame, 0.0))
    return sorted(owned.items())


def build_cut_result(
    batch: FrameBatchMetadata,
    detections: list[dict[str, Any]],
    state: CutSceneState,
    *,
    processing_ms: float,
) -> tuple[CutResultMessage, CutSceneState]:
    if batch.chunk_index != state.next_chunk_index:
        raise RuntimeError(
            "Cut chunks must be processed in order for stable scene IDs: "
            f"expected {state.next_chunk_index}, got {batch.chunk_index}"
        )

    cuts = _deduplicate_owned_cuts(batch, detections)
    scene_number = state.active_scene_number
    scene_start = batch.valid_start_frame
    transitions: list[Transition] = []
    scenes: list[SceneInterval] = []

    for cut_frame, confidence in cuts:
        scenes.append(
            SceneInterval(
                scene_id=f"{batch.task_id}:scene:{scene_number}",
                start_frame=scene_start,
                end_frame=cut_frame,
            )
        )
        transitions.append(
            Transition(
                type=TransitionType.HARD_CUT,
                frame=cut_frame,
                timestamp=cut_frame / batch.fps,
                confidence=confidence,
            )
        )
        scene_number += 1
        scene_start = cut_frame + 1

    if scene_start <= batch.valid_end_frame:
        scenes.append(
            SceneInterval(
                scene_id=f"{batch.task_id}:scene:{scene_number}",
                start_frame=scene_start,
                end_frame=batch.valid_end_frame,
            )
        )

    result = CutResultMessage(
        task_id=batch.task_id,
        chunk_id=batch.chunk_id,
        chunk_index=batch.chunk_index,
        object_ref=batch.object_ref,
        fps=batch.fps,
        context_start_frame=batch.context_start_frame,
        context_end_frame=batch.context_end_frame,
        valid_start_frame=batch.valid_start_frame,
        valid_end_frame=batch.valid_end_frame,
        transitions=transitions,
        scenes=scenes,
        is_last=batch.is_last,
        decode_ms=batch.decode_ms,
        cut_processing_ms=max(0.0, processing_ms),
    )
    return result, CutSceneState(
        next_chunk_index=batch.chunk_index + 1,
        active_scene_number=scene_number,
    )


def get_cut_inference_actor(ray: Any, settings: Settings) -> Any:
    actor_options: dict[str, Any] = {
        "num_gpus": settings.cut_model_num_gpus,
        "max_restarts": 3,
        "max_task_retries": 1,
    }
    if settings.cut_model_actor_resource:
        actor_options["resources"] = {settings.cut_model_actor_resource: 0.001}

    @ray.remote(**actor_options)
    class AutoShotInferenceActor:
        def __init__(
            self,
            weights_path: str,
            architecture_dir: str,
            threshold: float,
            allow_download: bool,
        ) -> None:
            from participant_4_cut_detection.autoshot_detector import (
                AutoShotDetector,
            )

            self.detector = AutoShotDetector(
                weights_path=weights_path,
                architecture_dir=architecture_dir,
                threshold=threshold,
                allow_download=allow_download,
            )

        def infer(self, wrapped_ref: list[Any]) -> dict[str, Any]:
            import ray as actor_ray

            if len(wrapped_ref) != 1:
                raise ValueError("Expected one nested Ray ObjectRef")
            frames = actor_ray.get(wrapped_ref[0])
            started = time.perf_counter()
            detections = self.detector.detect_cuts(frames)
            return {
                "detections": detections,
                "processing_ms": (time.perf_counter() - started) * 1_000,
            }

    return AutoShotInferenceActor.options(
        name=settings.cut_model_actor_name,
        namespace=ACTOR_NAMESPACE,
        lifetime="detached",
        get_if_exists=True,
    ).remote(
        str(settings.cut_model_weights_path),
        str(settings.cut_model_arch_dir),
        settings.cut_model_threshold,
        settings.cut_model_allow_download,
    )


class RealCutHandler:
    def __init__(self, settings: Settings, streams: RedisStreams) -> None:
        self.settings = settings
        self.streams = streams
        self.object_store = RayObjectStore(settings)
        self._actor: Any | None = None
        self._actor_lock = asyncio.Lock()

    async def _get_actor(self) -> Any:
        if self._actor is not None:
            return self._actor
        async with self._actor_lock:
            if self._actor is None:
                self._actor = await asyncio.to_thread(
                    get_cut_inference_actor,
                    self.object_store.ray,
                    self.settings,
                )
        return self._actor

    @staticmethod
    def _state_key(task_id: Any) -> str:
        return f"{CUT_STATE_PREFIX}:{task_id}"

    @staticmethod
    def _cache_key(task_id: Any, chunk_index: int) -> str:
        return f"{CUT_RESULT_CACHE_PREFIX}:{task_id}:{chunk_index:08d}"

    async def _load_state(self, batch: FrameBatchMetadata) -> CutSceneState:
        raw = await self.streams.client.hgetall(self._state_key(batch.task_id))
        if raw:
            return CutSceneState(
                next_chunk_index=int(raw["next_chunk_index"]),
                active_scene_number=int(raw["active_scene_number"]),
            )
        if batch.chunk_index == 0:
            return CutSceneState(next_chunk_index=0, active_scene_number=0)

        previous_key = f"cv:chunk:{batch.task_id}:{batch.chunk_index - 1:08d}"
        previous_payload = await self.streams.client.hget(previous_key, "cut_payload")
        if not previous_payload:
            raise RuntimeError(
                "Cannot rebuild cut scene state because the previous chunk result "
                "is not available yet"
            )
        previous = CutResultMessage.model_validate_json(previous_payload)
        if not previous.scenes:
            raise RuntimeError("Previous cut result has no scene interval")
        first_scene_number = _scene_number(previous.scenes[0].scene_id)
        return CutSceneState(
            next_chunk_index=batch.chunk_index,
            active_scene_number=first_scene_number + len(previous.transitions),
        )

    async def _persist_result(
        self,
        result: CutResultMessage,
        state: CutSceneState,
    ) -> None:
        pipeline = self.streams.client.pipeline(transaction=True)
        pipeline.set(
            self._cache_key(result.task_id, result.chunk_index),
            result.model_dump_json(),
            ex=self.settings.task_ttl_seconds,
        )
        pipeline.hset(
            self._state_key(result.task_id),
            mapping={
                "next_chunk_index": str(state.next_chunk_index),
                "active_scene_number": str(state.active_scene_number),
            },
        )
        pipeline.expire(self._state_key(result.task_id), self.settings.task_ttl_seconds)
        await pipeline.execute()

    async def _infer(self, batch: FrameBatchMetadata) -> dict[str, Any]:
        object_ref = await asyncio.to_thread(
            self.object_store.resolve_ref,
            batch.object_ref,
        )
        actor = await self._get_actor()
        result_ref = actor.infer.remote([object_ref])
        try:
            return await asyncio.to_thread(
                self.object_store.ray.get,
                result_ref,
                timeout=self.settings.ml_inference_timeout_seconds,
            )
        except Exception:
            # A restarted named actor receives a new incarnation. Drop the local
            # handle so the message retry resolves the current actor cleanly.
            async with self._actor_lock:
                self._actor = None
            raise

    async def __call__(self, message: StreamMessage) -> None:
        batch = stream_fields_to_model(message.fields, FrameBatchMetadata)
        cached = await self.streams.client.get(
            self._cache_key(batch.task_id, batch.chunk_index)
        )
        if cached:
            result = CutResultMessage.model_validate_json(cached)
        else:
            state = await self._load_state(batch)
            inference = await self._infer(batch)
            result, next_state = build_cut_result(
                batch,
                list(inference.get("detections", [])),
                state,
                processing_ms=float(inference.get("processing_ms", 0.0)),
            )
            await self._persist_result(result, next_state)

        await self.streams.publish(
            self.settings.stream_cut_results,
            model_to_stream_fields(result),
        )
        logger.info(
            "AutoShot chunk completed",
            extra={
                "task_id": str(batch.task_id),
                "chunk_index": batch.chunk_index,
                "transition_count": len(result.transitions),
            },
        )


def factory(settings: Settings, streams: RedisStreams) -> StreamWorker:
    return StreamWorker(
        worker_name="autoshot-cut",
        stream=settings.stream_video_chunks,
        group=settings.group_cut,
        handler=RealCutHandler(settings, streams),
        settings=settings,
        streams=streams,
        max_concurrency=settings.cut_worker_concurrency,
        partition_by_task=True,
    )


if __name__ == "__main__":
    asyncio.run(run_worker(factory))
